### ISSUE TITLE
Hadron-typeorm is generating wrong repository name for PascalCase class name

### ISSUE THREAD

**Issue by DanielMarkiel** [brainhubeu/hadron#45]
Hadron-typeorm is generating wrong repository name for PascalCase class name. 
E.g.
If we define models using the `Class + Decorators` option and the model name is `SomeModel`, the `repositoryName` function in the `connectionHelper` file is generating wrong repository name -> `someModelRepository`. Where it should return -> `somemodelRepository`. The whole class/model name should be lowercased.

**Comment by szymonbrainhub** [comment]
Thank You for reporting this issue. We will try to solve it as soon as we will have a spare resource. Also We strongly encourage You to look into this problem on Your own. All pull requests are more than welcome! We will inform You about the status of this issue in this thread.
