### ISSUE TITLE
Empty object in response

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [brainhubeu/hadron#8]
Hadron returns strings correctly, but when I return object in callback I always get empty object in the response.

Hadron configuration:
```javascript
hadron(
  app,
  [
    require('@brainhubeu/hadron-express'),
  ],
  {
    routes,
  },
))
```

Route:
```javascript
{
  getPost: {
    path: '/posts/:id',
    methods: ['GET'],
    callback: () => {
      return {
        title: 'Some title',
        content: 'Some content goes here',
        tags: [
          'one',
          'two',
          'three',
          4,
        ],
      };
    },
    middleware: [],
  },
}
```

Postman:
<img width="983" alt="screen shot 2018-05-15 at 09 33 23" src="https://user-images.githubusercontent.com/19817661/40042884-154c6b28-5823-11e8-8d61-a6d7657cd062.png">

Node version: 10.1.0
NPM version: 6.0.1
Hadron-core version: 0.0.2
Hadron-express version: 0.0.2

**Comment by Lukasz-pluszczewski** [comment]
This seems to be the intentional behavior:
You can return primitive value (like string, number null or undefined) and it will be sent as body. But to send JSON you need to return object with this interface:
```
interface IResponseSpec {
  status?: StatusCode;
  redirect?: string;
  headers?: IHeaders;
  body?: any;
  view?: IView;
}
```

Please, confirm if this was intended, and you can close this issue.

**Comment by caderek** [comment]
It's intentional: https://github.com/brainhubeu/hadron-docs/blob/master/src/routing.md#callback-with-non-primitive-response-body
